spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: 127.0.0.1
      port: 6379

app:
  jwt:
    access-token-ttl-seconds: 900
    refresh-token-ttl-seconds: 1209600
    secret: ${JWT_SECRET}