spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: paceleague-cache.vi34fu.ng.0001.apn2.cache.amazonaws.com
      port: 6379

app:
  jwt:
    access-token-ttl-seconds: 300
    refresh-token-ttl-seconds: 1209600
    secret: ${JWT_SECRET}