server:
  port: 8080
  forward-headers-strategy: framework
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false

app:
  jwt:
    issuer: paceleague
  media:
    bucket: paceleague-media

logging:
  level:
    org.springframework.security: DEBUG